### PR TITLE
Fix https://github.com/niieani/aurelia-template-lint-webpack-loader/issues/2

### LINKED ISSUE #2: Webpack 4 compat
@niieani please update the plugin to work with webpack 4.
Thanks

### PR DESCRIPTION
**Pull request by dweber019**
This fixes https://github.com/niieani/aurelia-template-lint-webpack-loader/issues/2

### CODE REVIEW

**Comment by dweber019** [comment]
@niieani could you merge this, thanks

**Comment by niieani** [comment]
Thanks

**Comment by dweber019** [comment]
Thank you, awaiting the release and then webpack 4 can come.

**Comment by dweber019** [comment]
@niieani could you do a release?

**Comment by niieani** [comment]
Hey @dweber019, not sure why didn't the automated release happen. I'll have to look into it.

**Comment by dweber019** [comment]
@niieani any news on the release?

**Comment by dweber019** [comment]
@niieani would be nice if you can check this again ;)

**Comment by niieani** [comment]
@dweber019 sorry about that, published as 1.1.0 now.

**Pull request merged**
